services:
  jaeger:
    image: jaegertracing/jaeger:2.14.1
    container_name: jaeger-standalone
    ports:
      - "16686:16686" # UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "5778:5778"   # agent config
      - "9411:9411"   # Zipkin


